# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Question(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Question()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuestion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Question
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Question
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Question
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Question
    def QuestionText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Question
    def QuestionDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Question
    def Answer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Question
    def AnswerDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Question
    def ClusterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def QuestionStart(builder):
    builder.StartObject(7)

def Start(builder):
    QuestionStart(builder)

def QuestionAddPos(builder, pos):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    QuestionAddPos(builder, pos)

def QuestionAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder, url):
    QuestionAddUrl(builder, url)

def QuestionAddQuestionText(builder, questionText):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(questionText), 0)

def AddQuestionText(builder, questionText):
    QuestionAddQuestionText(builder, questionText)

def QuestionAddQuestionDate(builder, questionDate):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(questionDate), 0)

def AddQuestionDate(builder, questionDate):
    QuestionAddQuestionDate(builder, questionDate)

def QuestionAddAnswer(builder, answer):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(answer), 0)

def AddAnswer(builder, answer):
    QuestionAddAnswer(builder, answer)

def QuestionAddAnswerDate(builder, answerDate):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(answerDate), 0)

def AddAnswerDate(builder, answerDate):
    QuestionAddAnswerDate(builder, answerDate)

def QuestionAddClusterId(builder, clusterId):
    builder.PrependInt16Slot(6, clusterId, 0)

def AddClusterId(builder, clusterId):
    QuestionAddClusterId(builder, clusterId)

def QuestionEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuestionEnd(builder)
