# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuestionBase(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuestionBase()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuestionBase(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuestionBase
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuestionBase
    def Questions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Question import Question
            obj = Question()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuestionBase
    def QuestionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuestionBase
    def QuestionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # QuestionBase
    def Clusters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cluster import Cluster
            obj = Cluster()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuestionBase
    def ClustersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuestionBase
    def ClustersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def QuestionBaseStart(builder):
    builder.StartObject(2)

def Start(builder):
    QuestionBaseStart(builder)

def QuestionBaseAddQuestions(builder, questions):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(questions), 0)

def AddQuestions(builder, questions):
    QuestionBaseAddQuestions(builder, questions)

def QuestionBaseStartQuestionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQuestionsVector(builder, numElems):
    return QuestionBaseStartQuestionsVector(builder, numElems)

def QuestionBaseAddClusters(builder, clusters):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(clusters), 0)

def AddClusters(builder, clusters):
    QuestionBaseAddClusters(builder, clusters)

def QuestionBaseStartClustersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartClustersVector(builder, numElems):
    return QuestionBaseStartClustersVector(builder, numElems)

def QuestionBaseEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuestionBaseEnd(builder)
