# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: questionbase.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'questionbase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12questionbase.proto\x12\x0f\x61\x62geordnetenmap\"4\n\x08Question\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x12\n\ncluster_id\x18\x03 \x01(\x05\"<\n\x07\x43luster\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\x02\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\x02\"h\n\x0cQuestionBase\x12,\n\tquestions\x18\x01 \x03(\x0b\x32\x19.abgeordnetenmap.Question\x12*\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x18.abgeordnetenmap.Clusterb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'questionbase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=39
  _globals['_QUESTION']._serialized_end=91
  _globals['_CLUSTER']._serialized_start=93
  _globals['_CLUSTER']._serialized_end=153
  _globals['_QUESTIONBASE']._serialized_start=155
  _globals['_QUESTIONBASE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
