# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cluster(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Cluster()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCluster(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Cluster
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cluster
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Cluster
    def Center(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Cluster
    def Topic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ClusterStart(builder):
    builder.StartObject(3)

def Start(builder):
    ClusterStart(builder)

def ClusterAddId(builder, id):
    builder.PrependInt16Slot(0, id, 0)

def AddId(builder, id):
    ClusterAddId(builder, id)

def ClusterAddCenter(builder, center):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(center), 0)

def AddCenter(builder, center):
    ClusterAddCenter(builder, center)

def ClusterAddTopic(builder, topic):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(topic), 0)

def AddTopic(builder, topic):
    ClusterAddTopic(builder, topic)

def ClusterEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClusterEnd(builder)
