// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Point } from './point.js';


export class Cluster {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Cluster {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCluster(bb:flatbuffers.ByteBuffer, obj?:Cluster):Cluster {
  return (obj || new Cluster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCluster(bb:flatbuffers.ByteBuffer, obj?:Cluster):Cluster {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Cluster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

center(obj?:Point):Point|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Point()).__init(this.bb_pos + offset, this.bb!) : null;
}

topic():string|null
topic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
topic(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCluster(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt16(0, id, 0);
}

static addCenter(builder:flatbuffers.Builder, centerOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, centerOffset, 0);
}

static addTopic(builder:flatbuffers.Builder, topicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, topicOffset, 0);
}

static endCluster(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
