// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cluster } from './cluster.js';
import { Question } from './question.js';


export class QuestionBase {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QuestionBase {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuestionBase(bb:flatbuffers.ByteBuffer, obj?:QuestionBase):QuestionBase {
  return (obj || new QuestionBase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuestionBase(bb:flatbuffers.ByteBuffer, obj?:QuestionBase):QuestionBase {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QuestionBase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

questions(index: number, obj?:Question):Question|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Question()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

questionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

clusters(index: number, obj?:Cluster):Cluster|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Cluster()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

clustersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startQuestionBase(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addQuestions(builder:flatbuffers.Builder, questionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, questionsOffset, 0);
}

static createQuestionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startQuestionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addClusters(builder:flatbuffers.Builder, clustersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, clustersOffset, 0);
}

static createClustersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startClustersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endQuestionBase(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishQuestionBaseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedQuestionBaseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createQuestionBase(builder:flatbuffers.Builder, questionsOffset:flatbuffers.Offset, clustersOffset:flatbuffers.Offset):flatbuffers.Offset {
  QuestionBase.startQuestionBase(builder);
  QuestionBase.addQuestions(builder, questionsOffset);
  QuestionBase.addClusters(builder, clustersOffset);
  return QuestionBase.endQuestionBase(builder);
}
}
